import {
  Customer,
  Service,
  InventoryItem,
  Appointment,
  Staff,
  AttendanceRecord,
  Promotion,
  Invoice,
  AppNotification
} from './types';

export const initialInventory: InventoryItem[] = [
  {
    id: 'inv-cotton',
    code: 'COT-IPEK-200',
    name: 'Bông Tẩy Trang Tròn Tiệt Trùng Ipek',
    category: 'Vật tư tiêu hao',
    brand: 'Ipek Turkey',
    packageType: 'Hộp 200 miếng',
    packageUnit: 'Hộp',
    subUnitsPerPackage: 200,
    subUnitName: 'miếng',
    packagePurchasePrice: 50000,
    costPerSubUnit: 250, // 50,000 / 200 = 250 VND/miếng
    stockPackages: 25,
    stockSubUnits: 5000,
    minThresholdSubUnits: 200,
    expiryDate: '2029-06-30',
    supplier: 'Nhà Phân Phối Bông Y Tế Việt Pháp',
    lastRestocked: '2026-08-20',
  },
  {
    id: 'inv-micellar',
    code: 'CLEAN-MICE-500',
    name: 'Nước Tẩy Trang Dịu Nhẹ Micellar Deep Cleansing',
    category: 'Tẩy trang & Rửa mặt',
    brand: 'Bioderma Pro',
    packageType: 'Chai 500ml',
    packageUnit: 'Chai',
    subUnitsPerPackage: 500,
    subUnitName: 'ml',
    packagePurchasePrice: 250000,
    costPerSubUnit: 500, // 250,000 / 500 = 500 VND/ml
    stockPackages: 10,
    stockSubUnits: 5000,
    minThresholdSubUnits: 300,
    expiryDate: '2028-04-15',
    supplier: 'Dược Phẩm Hoàng Mai',
    lastRestocked: '2026-08-18',
  },
  {
    id: 'inv-1',
    code: 'SER-ACNE-10',
    name: 'Serum Đặc Trị Mụn Tế Bào Gốc Hyaron',
    category: 'Tinh chất & Ampoule',
    brand: 'Geneworld Pharma',
    packageType: 'Hộp 10 ống',
    packageUnit: 'Hộp',
    subUnitsPerPackage: 10,
    subUnitName: 'ống (5ml)',
    packagePurchasePrice: 500000,
    costPerSubUnit: 50000, // 500,000 / 10 = 50,000 VND
    stockPackages: 12,
    stockSubUnits: 120,
    minThresholdSubUnits: 20,
    expiryDate: '2027-06-30',
    supplier: 'Công Ty Dược Mỹ Phẩm Á Châu',
    lastRestocked: '2026-08-10',
  },
  {
    id: 'inv-2',
    code: 'ALG-SPIRU-500',
    name: 'Bột Tảo Xoắn Tươi Spirulina Tự Nhiên',
    category: 'Mặt nạ & Bột đắp',
    brand: 'Organic Bio-Lab',
    packageType: 'Hũ 500g',
    packageUnit: 'Hũ',
    subUnitsPerPackage: 500,
    subUnitName: 'gram (g)',
    packagePurchasePrice: 650000,
    costPerSubUnit: 1300, // 650,000 / 500 = 1,300 VND/gram
    stockPackages: 8,
    stockSubUnits: 4000,
    minThresholdSubUnits: 500,
    expiryDate: '2027-12-15',
    supplier: 'Bio Beauty Vietnam',
    lastRestocked: '2026-08-12',
  },
  {
    id: 'inv-3',
    code: 'OIL-HERB-1000',
    name: 'Tinh Dầu Massage Gừng Thảo Dược Đông Y',
    category: 'Tinh dầu massage',
    brand: 'Mộc Linh Thảo',
    packageType: 'Chai 1000ml',
    packageUnit: 'Chai',
    subUnitsPerPackage: 1000,
    subUnitName: 'ml',
    packagePurchasePrice: 450000,
    costPerSubUnit: 450, // 450,000 / 1000 = 450 VND/ml
    stockPackages: 6,
    stockSubUnits: 6000,
    minThresholdSubUnits: 800,
    expiryDate: '2028-01-20',
    supplier: 'Dược Liệu Thuần Chay VN',
    lastRestocked: '2026-07-28',
  },
  {
    id: 'inv-4',
    code: 'CAP-DETOX-100',
    name: 'Viên Nang Thải Chì Tố Hạt Nén',
    category: 'Mỹ phẩm thải độc',
    brand: 'DermaCare Korea',
    packageType: 'Hộp 100 viên',
    packageUnit: 'Hộp',
    subUnitsPerPackage: 100,
    subUnitName: 'viên',
    packagePurchasePrice: 350000,
    costPerSubUnit: 3500,
    stockPackages: 5,
    stockSubUnits: 500,
    minThresholdSubUnits: 80,
    expiryDate: '2027-09-18',
    supplier: 'Korea Beauty Dist',
    lastRestocked: '2026-08-01',
  },
  {
    id: 'inv-5',
    code: 'GEL-LASER-5L',
    name: 'Gel Siêu Âm Lạnh Triệt Lông Diode Laser',
    category: 'Gel & Dung môi máy',
    brand: 'UltraCool Medi',
    packageType: 'Can 5000ml',
    packageUnit: 'Can',
    subUnitsPerPackage: 5000,
    subUnitName: 'ml',
    packagePurchasePrice: 200000,
    costPerSubUnit: 40, // 200,000 / 5000 = 40 VND/ml
    stockPackages: 15,
    stockSubUnits: 75000,
    minThresholdSubUnits: 5000,
    expiryDate: '2028-05-10',
    supplier: 'Thiết Bị Y Tế Sài Gòn',
    lastRestocked: '2026-08-15',
  },
  {
    id: 'inv-6',
    code: 'DISP-KIT-SET',
    name: 'Set Găng Tay & Dụng Cụ Y Tế Vô Trùng',
    category: 'Dụng cụ tiêu hao',
    brand: 'MediClean',
    packageType: 'Thùng 100 bộ',
    packageUnit: 'Thùng',
    subUnitsPerPackage: 100,
    subUnitName: 'bộ set',
    packagePurchasePrice: 600000,
    costPerSubUnit: 6000,
    stockPackages: 4,
    stockSubUnits: 400,
    minThresholdSubUnits: 50,
    expiryDate: '2029-01-01',
    supplier: 'Vật Tư Y Tế Phúc An',
    lastRestocked: '2026-08-05',
  },
  {
    id: 'inv-7',
    code: 'SHAMP-HERB-5L',
    name: 'Dầu Gội Bồ Kết Thảo Mộc Dưỡng Sinh',
    category: 'Chăm sóc tóc & da đầu',
    brand: 'Cỏ Mềm Homelab',
    packageType: 'Can 5000ml',
    packageUnit: 'Can',
    subUnitsPerPackage: 5000,
    subUnitName: 'ml',
    packagePurchasePrice: 600000,
    costPerSubUnit: 120, // 600,000 / 5000 = 120 VND/ml
    stockPackages: 2,
    stockSubUnits: 10000,
    minThresholdSubUnits: 1000,
    expiryDate: '2027-11-20',
    supplier: 'Cỏ Mềm Herb Factory',
    lastRestocked: '2026-07-20',
  },
  {
    id: 'inv-mask-comp',
    code: 'MASK-COMP-100',
    name: 'Mặt Nạ Giấy Nén Cấp Ẩm Thảo Dược',
    category: 'Mặt nạ & Bột đắp',
    brand: 'Miniso Beauty Pro',
    packageType: 'Túi 100 viên',
    packageUnit: 'Túi',
    subUnitsPerPackage: 100,
    subUnitName: 'viên',
    packagePurchasePrice: 800000,
    costPerSubUnit: 800, // 80,000 / 100 = 800 VND/viên
    stockPackages: 12,
    stockSubUnits: 1200,
    minThresholdSubUnits: 100,
    expiryDate: '2028-09-30',
    supplier: 'Mỹ Phẩm Xanh',
    lastRestocked: '2026-08-16',
  }
];

export const initialServices: Service[] = [
  {
    id: 'srv-1',
    name: 'Trị Mụn Chuyên Sâu Chuẩn Y Khoa 12 Bước',
    category: 'Chăm sóc & Điều trị da mặt',
    durationMinutes: 75,
    price: 450000,
    description: 'Lấy nhân mụn y khoa vô khuẩn, điện di tinh chất phục hồi, chiếu ánh sáng sinh học Bio-Light kháng viêm.',
    image: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=400&q=80',
    costItems: [
      {
        inventoryItemId: 'inv-cotton',
        name: 'Bông Tẩy Trang Tiệt Trùng Ipek (Hộp 200 miếng)',
        unit: 'miếng',
        quantityUsed: 4,
        costPerUnit: 250,
        totalCost: 1000,
      },
      {
        inventoryItemId: 'inv-micellar',
        name: 'Nước Tẩy Trang Micellar (Chai 500ml)',
        unit: 'ml',
        quantityUsed: 10,
        costPerUnit: 500,
        totalCost: 5000,
      },
      {
        inventoryItemId: 'inv-1',
        name: 'Serum Tế Bào Gốc Hyaron (Hộp 10 ống)',
        unit: 'ống (5ml)',
        quantityUsed: 1,
        costPerUnit: 50000,
        totalCost: 50000,
      },
      {
        inventoryItemId: 'inv-6',
        name: 'Set Găng Tay & Dụng Cụ Vô Trùng',
        unit: 'bộ set',
        quantityUsed: 1,
        costPerUnit: 6000,
        totalCost: 6000,
      }
    ],
    technicianCommission: 60000,
    otherOverheads: 25000, // Điện máy ánh sáng sinh học, giặt sấy khăn ga
    totalCalculatedCost: 147000, // 1k + 5k + 50k + 6k + 60k + 25k = 147,000 VND
    grossProfit: 303000, // 450k - 147k = 303,000 VND
    profitMarginPercent: 67.3,
  },
  {
    id: 'srv-2',
    name: 'Cấy Tảo Xoắn Tươi Collagen Căng Bóng Da',
    category: 'Chăm sóc & Điều trị da mặt',
    durationMinutes: 60,
    price: 550000,
    description: 'Phi kim nano cấy tinh chất tảo xoắn biển sâu kết hợp collagen thủy phân cấp ẩm tức thì, mờ thâm nám.',
    image: 'https://images.unsplash.com/photo-1512290900672-1f48641ebca9?w=400&q=80',
    costItems: [
      {
        inventoryItemId: 'inv-cotton',
        name: 'Bông Tẩy Trang Tiệt Trùng Ipek (Hộp 200 miếng)',
        unit: 'miếng',
        quantityUsed: 6,
        costPerUnit: 250,
        totalCost: 1500,
      },
      {
        inventoryItemId: 'inv-2',
        name: 'Bột Tảo Xoắn Tươi Spirulina (Hũ 500g)',
        unit: 'gram (g)',
        quantityUsed: 10,
        costPerUnit: 1300,
        totalCost: 13000,
      },
      {
        inventoryItemId: 'inv-1',
        name: 'Serum Phục Hồi Da Hyaron (Hộp 10 ống)',
        unit: 'ống (5ml)',
        quantityUsed: 0.5,
        costPerUnit: 50000,
        totalCost: 25000,
      },
      {
        inventoryItemId: 'inv-6',
        name: 'Set Găng Tay & Kim Nano Tiêu Hao',
        unit: 'bộ set',
        quantityUsed: 1,
        costPerUnit: 6000,
        totalCost: 6000,
      }
    ],
    technicianCommission: 70000,
    otherOverheads: 30000,
    totalCalculatedCost: 145500,
    grossProfit: 404500,
    profitMarginPercent: 73.5,
  },
  {
    id: 'srv-3',
    name: 'Massage Body Toàn Thân Đá Nóng & Tinh Dầu Gừng',
    category: 'Massage & Thư giãn Body',
    durationMinutes: 90,
    price: 490000,
    description: 'Khai thông kinh lạc, ấn huyệt giải tỏa đau mỏi vai gáy và chườm đá nóng bazan tự nhiên giải phóng cơ bắp.',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=400&q=80',
    costItems: [
      {
        inventoryItemId: 'inv-3',
        name: 'Tinh Dầu Massage Gừng Thảo Dược (Chai 1000ml)',
        unit: 'ml',
        quantityUsed: 40,
        costPerUnit: 450,
        totalCost: 18000,
      },
      {
        inventoryItemId: 'inv-6',
        name: 'Khăn trải spa & đồ cotton xông hơi',
        unit: 'bộ set',
        quantityUsed: 1,
        costPerUnit: 6000,
        totalCost: 6000,
      }
    ],
    technicianCommission: 90000,
    otherOverheads: 40000, // Nồi hấp đá nóng, xông hơi tinh dầu
    totalCalculatedCost: 154000,
    grossProfit: 336000,
    profitMarginPercent: 68.6,
  },
  {
    id: 'srv-4',
    name: 'Hút Chì Thải Độc Tố & Điện Di Vitamin C',
    category: 'Chăm sóc & Điều trị da mặt',
    durationMinutes: 60,
    price: 390000,
    description: 'Công nghệ sóng siêu âm rung đẩy chì và bụi mịn ẩn sâu dưới lỗ chân lông, phục hồi sắc diện hồng hào.',
    image: 'https://images.unsplash.com/photo-1519699047748-de8e457a634e?w=400&q=80',
    costItems: [
      {
        inventoryItemId: 'inv-cotton',
        name: 'Bông Tẩy Trang Tiệt Trùng Ipek (Hộp 200 miếng)',
        unit: 'miếng',
        quantityUsed: 4,
        costPerUnit: 250,
        totalCost: 1000,
      },
      {
        inventoryItemId: 'inv-4',
        name: 'Viên Nang Thải Chì DermaCare (Hộp 100 viên)',
        unit: 'viên',
        quantityUsed: 2,
        costPerUnit: 3500,
        totalCost: 7000,
      },
      {
        inventoryItemId: 'inv-6',
        name: 'Set Tiêu Hao Vệ Sinh Y Tế',
        unit: 'bộ set',
        quantityUsed: 1,
        costPerUnit: 6000,
        totalCost: 6000,
      }
    ],
    technicianCommission: 50000,
    otherOverheads: 25000,
    totalCalculatedCost: 89000,
    grossProfit: 301000,
    profitMarginPercent: 77.2,
  },
  {
    id: 'srv-5',
    name: 'Gội Đầu Dưỡng Sinh Trung Hoa 9 Bước Thảo Mộc',
    category: 'Dưỡng sinh & Chăm sóc tóc',
    durationMinutes: 75,
    price: 280000,
    description: 'Massage vùng đầu, cổ vai gáy, rửa mặt thảo dược, đắp mắt ngải cứu và canh thảo dược bài độc dưỡng tóc.',
    image: 'https://images.unsplash.com/photo-1560750588-73207b1ef5b8?w=400&q=80',
    costItems: [
      {
        inventoryItemId: 'inv-cotton',
        name: 'Bông Tẩy Trang Tiệt Trùng Ipek (Hộp 200 miếng)',
        unit: 'miếng',
        quantityUsed: 2,
        costPerUnit: 250,
        totalCost: 500,
      },
      {
        inventoryItemId: 'inv-7',
        name: 'Dầu Gội Bồ Kết Thảo Mộc Cỏ Mềm (Can 5000ml)',
        unit: 'ml',
        quantityUsed: 50,
        costPerUnit: 120,
        totalCost: 6000,
      },
      {
        inventoryItemId: 'inv-6',
        name: 'Khăn bông ủ ấm & bông bịt tai',
        unit: 'bộ set',
        quantityUsed: 1,
        costPerUnit: 6000,
        totalCost: 6000,
      }
    ],
    technicianCommission: 50000,
    otherOverheads: 25000,
    totalCalculatedCost: 87500,
    grossProfit: 192500,
    profitMarginPercent: 68.8,
  },
  {
    id: 'srv-6',
    name: 'Triệt Lông Nách / Mép Diode Laser Ice Plus',
    category: 'Triệt lông công nghệ cao',
    durationMinutes: 30,
    price: 350000,
    description: 'Đầu làm lạnh -5 độ C không đau rát, triệt tiêu nang lông tận gốc và se khít lỗ chân lông, sáng mịn da.',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=400&q=80',
    costItems: [
      {
        inventoryItemId: 'inv-cotton',
        name: 'Bông Tẩy Trang Tiệt Trùng Ipek (Hộp 200 miếng)',
        unit: 'miếng',
        quantityUsed: 2,
        costPerUnit: 250,
        totalCost: 500,
      },
      {
        inventoryItemId: 'inv-5',
        name: 'Gel Siêu Âm Lạnh Triệt Lông (Can 5000ml)',
        unit: 'ml',
        quantityUsed: 100,
        costPerUnit: 40,
        totalCost: 4000,
      },
      {
        inventoryItemId: 'inv-6',
        name: 'Dao cạo y tế & khăn giấy vô khuẩn',
        unit: 'bộ set',
        quantityUsed: 1,
        costPerUnit: 6000,
        totalCost: 6000,
      }
    ],
    technicianCommission: 40000,
    otherOverheads: 35000, // Khấu hao bóng xung laser Diode
    totalCalculatedCost: 85500,
    grossProfit: 264500,
    profitMarginPercent: 75.6,
  }
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Nguyễn Thị Mai Anh',
    phone: '0912 345 678',
    email: 'maianh.nguyen@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
    gender: 'female',
    birthDate: '1995-04-12',
    joinDate: '2025-03-15',
    tier: 'VIP',
    totalSpent: 8450000,
    loyaltyPoints: 845,
    skinType: 'Da dầu mụn, nhạy cảm vùng chữ T',
    allergies: 'Dị ứng cồn khô và hương liệu nhân tạo',
    notes: 'Thích kỹ thuật viên massage lực vừa, dùng gối thảo dược ấm',
    treatmentHistory: [
      {
        id: 'treat-1',
        date: '2026-08-20',
        serviceId: 'srv-1',
        serviceName: 'Trị Mụn Chuyên Sâu Chuẩn Y Khoa 12 Bước',
        technicianName: 'Trần Thị Thu Thảo',
        notes: 'Đã lấy sạch nhân mụn cám, da giảm viêm sưng 70%',
        skinCondition: 'Tốt, hết đỏ sau chiếu đèn vàng',
        cost: 450000,
      },
      {
        id: 'treat-2',
        date: '2026-08-05',
        serviceId: 'srv-2',
        serviceName: 'Cấy Tảo Xoắn Tươi Collagen Căng Bóng Da',
        technicianName: 'Lê Hoàng Yến',
        notes: 'Liệu trình thứ 2, da sáng và mọng nước hơn',
        skinCondition: 'Lỗ chân lông se khít rõ rệt',
        cost: 550000,
      }
    ]
  },
  {
    id: 'cust-2',
    name: 'Trần Bảo Ngọc',
    phone: '0988 765 432',
    email: 'baongoc.tran@yahoo.com',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80',
    gender: 'female',
    birthDate: '1992-09-28',
    joinDate: '2025-06-10',
    tier: 'Diamond',
    totalSpent: 16800000,
    loyaltyPoints: 1680,
    skinType: 'Da khô lão hóa nhẹ, có vết đốm nâu vùng gò má',
    allergies: 'Không có dị ứng',
    notes: 'Khách hàng thân thiết VIP, ưu tiên phòng VIP 1',
    treatmentHistory: [
      {
        id: 'treat-3',
        date: '2026-08-22',
        serviceId: 'srv-3',
        serviceName: 'Massage Body Toàn Thân Đá Nóng & Tinh Dầu Gừng',
        technicianName: 'Phạm Hồng Nhung',
        notes: 'Tập trung giải tỏa vùng cơ vai và thắt lưng',
        skinCondition: 'Khỏe mạnh, tuần hoàn máu tốt',
        cost: 490000,
      }
    ]
  },
  {
    id: 'cust-3',
    name: 'Đặng Minh Quân',
    phone: '0903 112 233',
    email: 'minhquan.dang@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    gender: 'male',
    birthDate: '1990-11-04',
    joinDate: '2026-01-20',
    tier: 'Gold',
    totalSpent: 4200000,
    loyaltyPoints: 420,
    skinType: 'Da hỗn hợp thiên dầu, bít tắc chân lông do tập gym',
    allergies: 'Dị ứng nhẹ tinh dầu quế nồng',
    notes: 'Đặt lịch định kỳ thứ 7 hàng tuần',
    treatmentHistory: [
      {
        id: 'treat-4',
        date: '2026-08-18',
        serviceId: 'srv-4',
        serviceName: 'Hút Chì Thải Độc Tố & Điện Di Vitamin C',
        technicianName: 'Trần Thị Thu Thảo',
        notes: 'Đã hút sạch cặn chì, da sáng bật tông',
        skinCondition: 'Cải thiện độ đàn hồi',
        cost: 390000,
      }
    ]
  },
  {
    id: 'cust-4',
    name: 'Vũ Hoàng Thảo Vy',
    phone: '0934 556 778',
    email: 'thaovy.vu@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&q=80',
    gender: 'female',
    birthDate: '2001-08-19',
    joinDate: '2026-07-01',
    tier: 'Silver',
    totalSpent: 1850000,
    loyaltyPoints: 185,
    skinType: 'Da thường, có nhiều sợi bã nhờn',
    allergies: 'Không',
    notes: 'Sinh viên, quan tâm các gói khuyến mãi',
    treatmentHistory: [
      {
        id: 'treat-5',
        date: '2026-08-15',
        serviceId: 'srv-5',
        serviceName: 'Gội Đầu Dưỡng Sinh Trung Hoa 9 Bước Thảo Mộc',
        technicianName: 'Lê Hoàng Yến',
        notes: 'Gội sạch mượt tóc, ủ mặt nạ dưa leo',
        skinCondition: 'Tốt',
        cost: 280000,
      }
    ]
  }
];

export const initialStaff: Staff[] = [
  {
    id: 'st-1',
    name: 'Trần Thị Thu Thảo',
    phone: '0918 889 901',
    email: 'thuthao.spa@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&q=80',
    role: 'technician',
    positionTitle: 'Trưởng Nhóm Kỹ Thuật Viên Da Liễu',
    specialty: ['Điều trị mụn chuẩn Y Khoa', 'Cấy tế bào gốc nano', 'Phi kim tái tạo'],
    baseSalary: 8500000,
    commissionRate: 15,
    rating: 4.9,
    status: 'active',
    startDate: '2024-03-15',
    seniorityBonusAmount: 500000,
    notes: 'Nhân viên ưu tú, có thâm niên trên 2 năm, tay nghề kỹ thuật xuất sắc.',
    completedServicesCount: 84,
    monthlyCommission: 4850000,
  },
  {
    id: 'st-2',
    name: 'Lê Hoàng Yến',
    phone: '0922 334 455',
    email: 'hoangyen.spa@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=200&q=80',
    role: 'technician',
    positionTitle: 'Chuyên Viên Dưỡng Sinh & Chăm Sóc Da',
    specialty: ['Gội đầu dưỡng sinh', 'Thải độc da', 'Massage bấm huyệt'],
    baseSalary: 7500000,
    commissionRate: 15,
    rating: 4.8,
    status: 'active',
    startDate: '2025-01-10',
    seniorityBonusAmount: 0,
    notes: 'Kỹ năng giao tiếp khách hàng tốt, làm việc chăm chỉ.',
    completedServicesCount: 72,
    monthlyCommission: 3920000,
  },
  {
    id: 'st-3',
    name: 'Phạm Hồng Nhung',
    phone: '0933 667 788',
    email: 'hongnhung.spa@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80',
    role: 'technician',
    positionTitle: 'Master Massage Body & Công Nghệ Cao',
    specialty: ['Massage Body đá nóng', 'Triệt lông Diode Laser', 'Giảm béo'],
    baseSalary: 8000000,
    commissionRate: 15,
    rating: 4.95,
    status: 'active',
    startDate: '2024-08-20',
    seniorityBonusAmount: 500000,
    notes: 'Master massage body, khách VIP thường xuyên yêu cầu đích danh.',
    completedServicesCount: 65,
    monthlyCommission: 4200000,
  },
  {
    id: 'st-4',
    name: 'Nguyễn Thị Hương Giang',
    phone: '0944 112 299',
    email: 'huonggiang.spa@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=200&q=80',
    role: 'receptionist',
    positionTitle: 'Trưởng Quầy Lễ Tân & Thu Ngân',
    specialty: ['Tư vấn dịch vụ', 'Chăm sóc khách hàng VIP', 'Thu ngân & xuất hóa đơn'],
    baseSalary: 8000000,
    commissionRate: 5,
    rating: 4.9,
    status: 'active',
    startDate: '2024-05-02',
    seniorityBonusAmount: 500000,
    notes: 'Điều phối ca tour chuyên nghiệp, xử lý thanh toán chính xác.',
    completedServicesCount: 0,
    monthlyCommission: 1800000,
  },
  {
    id: 'st-5',
    name: 'Hoàng Quốc Bảo',
    phone: '0909 888 777',
    email: 'baoquoc.owner@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80',
    role: 'owner',
    positionTitle: 'Tổng Giám Đốc / Chủ Spa',
    specialty: ['Quản trị chiến lược', 'Phát triển thương hiệu'],
    baseSalary: 30000000,
    commissionRate: 0,
    rating: 5.0,
    status: 'active',
    startDate: '2023-01-01',
    seniorityBonusAmount: 0,
    notes: 'Sáng lập & điều hành chuỗi Spa.',
    completedServicesCount: 0,
    monthlyCommission: 0,
  },
  {
    id: 'st-archived-1',
    name: 'Nguyễn Thúy Quỳnh',
    phone: '0977 445 566',
    email: 'thuyquynh.former@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
    role: 'technician',
    positionTitle: 'Cựu Kỹ Thuật Viên Chăm Sóc Da (Đã Nghỉ Việc)',
    specialty: ['Trị mụn', 'Hút chì', 'Cấy tảo xoắn'],
    baseSalary: 7000000,
    commissionRate: 15,
    rating: 4.75,
    status: 'resigned',
    startDate: '2023-06-15',
    endDate: '2026-04-30',
    resignationReason: 'Chuyển nơi cư trú về quê Đà Nẵng mở tiệm riêng',
    seniorityBonusAmount: 0,
    notes: 'Đã hoàn tất bàn giao đồng phục, dụng cụ và chốt sổ lương cuối cùng.',
    completedServicesCount: 142,
    monthlyCommission: 0,
  },
  {
    id: 'st-archived-2',
    name: 'Đặng Ngọc Thảo My',
    phone: '0966 223 344',
    email: 'thaomy.former@gmail.com',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&q=80',
    role: 'receptionist',
    positionTitle: 'Cựu Nhân Viên Tư Vấn & Lễ Tân (Đã Nghỉ Việc)',
    specialty: ['Tư vấn mỹ phẩm', 'Chốt sale liệu trình'],
    baseSalary: 7200000,
    commissionRate: 5,
    rating: 4.6,
    status: 'resigned',
    startDate: '2024-02-01',
    endDate: '2025-11-30',
    resignationReason: 'Học lên cao học ngành Quản trị dịch vụ',
    seniorityBonusAmount: 0,
    notes: 'Đã bàn giao danh sách khách hàng VIP cho Giang tiếp nhận.',
    completedServicesCount: 0,
    monthlyCommission: 0,
  }
];

export const initialAppointments: Appointment[] = [
  {
    id: 'apt-1',
    customerId: 'cust-1',
    customerName: 'Nguyễn Thị Mai Anh',
    customerPhone: '0912 345 678',
    customerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&q=80',
    serviceId: 'srv-1',
    serviceName: 'Trị Mụn Chuyên Sâu Chuẩn Y Khoa 12 Bước',
    servicePrice: 450000,
    staffId: 'st-1',
    staffName: 'Trần Thị Thu Thảo',
    roomBed: 'Phòng VIP 01 - Giường 2',
    date: '2026-08-25',
    time: '09:30',
    duration: 75,
    status: 'in_progress',
    notes: 'Khách yêu cầu nặn kỹ vùng cằm và trán',
    paid: false,
  },
  {
    id: 'apt-2',
    customerId: 'cust-2',
    customerName: 'Trần Bảo Ngọc',
    customerPhone: '0988 765 432',
    customerAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&q=80',
    serviceId: 'srv-3',
    serviceName: 'Massage Body Toàn Thân Đá Nóng & Tinh Dầu Gừng',
    servicePrice: 490000,
    staffId: 'st-3',
    staffName: 'Phạm Hồng Nhung',
    roomBed: 'Phòng Body Thảo Dược - Giường 1',
    date: '2026-08-25',
    time: '11:00',
    duration: 90,
    status: 'arrived',
    notes: 'Khách đến sớm 10 phút, đang uống trà thảo mộc tiếp đón',
    paid: false,
  },
  {
    id: 'apt-3',
    customerId: 'cust-3',
    customerName: 'Đặng Minh Quân',
    customerPhone: '0903 112 233',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80',
    serviceId: 'srv-4',
    serviceName: 'Hút Chì Thải Độc Tố & Điện Di Vitamin C',
    servicePrice: 390000,
    staffId: 'st-1',
    staffName: 'Trần Thị Thu Thảo',
    roomBed: 'Phòng Trị Liệu Da 02 - Giường 1',
    date: '2026-08-25',
    time: '14:30',
    duration: 60,
    status: 'confirmed',
    notes: 'Đã gọi điện xác nhận lịch hẹn trước 2 tiếng',
    paid: false,
  },
  {
    id: 'apt-4',
    customerId: 'cust-4',
    customerName: 'Vũ Hoàng Thảo Vy',
    customerPhone: '0934 556 778',
    customerAvatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&q=80',
    serviceId: 'srv-5',
    serviceName: 'Gội Đầu Dưỡng Sinh Trung Hoa 9 Bước Thảo Mộc',
    servicePrice: 280000,
    staffId: 'st-2',
    staffName: 'Lê Hoàng Yến',
    roomBed: 'Khu Gội Dưỡng Sinh - Giường 3',
    date: '2026-08-25',
    time: '16:00',
    duration: 75,
    status: 'confirmed',
    notes: 'Có mã voucher giảm 20% sinh viên',
    paid: false,
  }
];

export const initialPromotions: Promotion[] = [
  {
    id: 'promo-1',
    code: 'SPASUMMER20',
    title: 'Đại Tiệc Trẻ Hóa Da Mùa Hè - Giảm 20%',
    description: 'Giảm 20% cho tất cả dịch vụ Chăm sóc & Cấy tảo tái sinh da mặt.',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 400000,
    maxDiscount: 200000,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    usageLimit: 100,
    usedCount: 42,
    status: 'active',
    targetTier: 'All',
    bannerColor: 'from-amber-500 to-rose-500',
  },
  {
    id: 'promo-2',
    code: 'VIPDIAMOND100K',
    title: 'Tri Ân Khách Hàng VIP - Tặng Ngay 100.000đ',
    description: 'Giảm trực tiếp 100,000 VND trên tổng hóa đơn dịch vụ Massage & Liệu trình cao cấp.',
    discountType: 'fixed_amount',
    discountValue: 100000,
    minOrderValue: 450000,
    startDate: '2026-08-15',
    endDate: '2026-09-15',
    usageLimit: 50,
    usedCount: 18,
    status: 'active',
    targetTier: 'VIP',
    bannerColor: 'from-purple-600 to-indigo-600',
  },
  {
    id: 'promo-3',
    code: 'BIRTHDAY50K',
    title: 'Mừng Sinh Nhật Ngọt Ngào - Tặng 50K & Trà Hoa Cúc',
    description: 'Ưu đãi dành riêng cho quý khách hàng có ngày sinh trong tháng hiện tại.',
    discountType: 'fixed_amount',
    discountValue: 50000,
    minOrderValue: 250000,
    startDate: '2026-08-01',
    endDate: '2026-08-31',
    usageLimit: 200,
    usedCount: 29,
    status: 'active',
    targetTier: 'All',
    bannerColor: 'from-emerald-500 to-teal-700',
  }
];

export const initialAttendance: AttendanceRecord[] = [
  {
    id: 'att-1',
    staffId: 'st-1',
    staffName: 'Trần Thị Thu Thảo',
    date: '2026-08-25',
    shift: 'morning',
    clockInTime: '08:25',
    status: 'on_time',
    workingHours: 6.0,
    notes: 'Check-in bằng vân tay tại quầy lễ tân',
  },
  {
    id: 'att-2',
    staffId: 'st-2',
    staffName: 'Lê Hoàng Yến',
    date: '2026-08-25',
    shift: 'morning',
    clockInTime: '08:28',
    status: 'on_time',
    workingHours: 6.0,
    notes: 'Đúng giờ',
  },
  {
    id: 'att-3',
    staffId: 'st-3',
    staffName: 'Phạm Hồng Nhung',
    date: '2026-08-25',
    shift: 'morning',
    clockInTime: '08:40',
    status: 'late',
    workingHours: 5.75,
    notes: 'Kẹt xe đường Nguyễn Huệ, đã báo quản lý trước',
  },
  {
    id: 'att-4',
    staffId: 'st-4',
    staffName: 'Nguyễn Thị Hương Giang',
    date: '2026-08-25',
    shift: 'morning',
    clockInTime: '08:15',
    status: 'on_time',
    workingHours: 6.2,
    notes: 'Mở cửa spa, chuẩn bị trà welcome tiếp khách',
  }
];

export const initialInvoices: Invoice[] = [
  {
    id: 'inv-rec-1',
    code: 'HD-20260824-001',
    customerId: 'cust-1',
    customerName: 'Nguyễn Thị Mai Anh',
    customerPhone: '0912 345 678',
    staffId: 'st-1',
    staffName: 'Trần Thị Thu Thảo',
    date: '2026-08-24 16:45',
    items: [
      {
        serviceId: 'srv-1',
        serviceName: 'Trị Mụn Chuyên Sâu Chuẩn Y Khoa 12 Bước',
        quantity: 1,
        price: 450000,
      }
    ],
    subtotal: 450000,
    discountAmount: 90000,
    voucherCode: 'SPASUMMER20',
    taxAmount: 0,
    tipAmount: 50000,
    totalAmount: 410000,
    paymentMethod: 'vietqr',
    status: 'paid',
    notes: 'Đã thanh toán qua VietQR Vietcombank - Mã GD: 994829',
  },
  {
    id: 'inv-rec-2',
    code: 'HD-20260824-002',
    customerId: 'cust-2',
    customerName: 'Trần Bảo Ngọc',
    customerPhone: '0988 765 432',
    staffId: 'st-3',
    staffName: 'Phạm Hồng Nhung',
    date: '2026-08-24 18:20',
    items: [
      {
        serviceId: 'srv-3',
        serviceName: 'Massage Body Toàn Thân Đá Nóng & Tinh Dầu Gừng',
        quantity: 1,
        price: 490000,
      },
      {
        serviceId: 'srv-5',
        serviceName: 'Gội Đầu Dưỡng Sinh Trung Hoa 9 Bước Thảo Mộc',
        quantity: 1,
        price: 280000,
      }
    ],
    subtotal: 770000,
    discountAmount: 100000,
    voucherCode: 'VIPDIAMOND100K',
    taxAmount: 0,
    tipAmount: 100000,
    totalAmount: 770000,
    paymentMethod: 'momo',
    status: 'paid',
    notes: 'Thanh toán MoMo thành công',
  }
];

export const initialNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'Cảnh báo tồn kho mỹ phẩm',
    message: 'Serum Tế Bào Gốc Hyaron chỉ còn 12 ống, đã chạm ngưỡng cảnh báo tối thiểu (20 ống). Vui lòng nhập hàng sớm!',
    timestamp: '10 phút trước',
    type: 'inventory',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Khách VIP vừa đặt lịch hẹn mới',
    message: 'Khách hàng Trần Bảo Ngọc (Diamond) đặt lịch Massage Body Đá Nóng lúc 11:00 hôm nay.',
    timestamp: '35 phút trước',
    type: 'booking',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Chiến dịch khuyến mãi mùa hè',
    message: 'Đã gửi thành công 85 tin thông báo mã SPASUMMER20 tới khách hàng trên ứng dụng.',
    timestamp: '2 giờ trước',
    type: 'promo',
    read: true,
  }
];
